# Generated by Django 5.2.3 on 2025-06-11 06:06

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='founder_image',
            field=models.ImageField(upload_to='founders/', verbose_name='Фото основателя'),
        ),
        migrations.AlterField(
            model_name='about',
            name='founder_name',
            field=models.CharField(max_length=100, verbose_name='Имя основателя'),
        ),
        migrations.AlterField(
            model_name='about',
            name='founder_role',
            field=models.CharField(max_length=100, verbose_name='Должность основателя'),
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subheading',
            field=models.TextField(verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='dizain',
            name='image',
            field=models.ImageField(upload_to='dizain/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='dizain',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dizain',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Design', 'Дизайн'), ('Management', 'Менеджмент'), ('SMM', 'SMM')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=10, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('Remote', 'Удалённо'), ('Office', 'Офис'), ('Hybrid', 'Гибридный график'), ('Full-time', 'Полный рабочий день')], max_length=20, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='file',
            field=models.FileField(upload_to='resumes/', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.job', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на LinkedIn'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='meropriyatie',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='meropriyatie',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='meropriyatie',
            name='image',
            field=models.ImageField(upload_to='meropriyatie/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='meropriyatie',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='meropriyatie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to='tools/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='review/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon',
            field=models.ImageField(upload_to='tools/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
