# Generated by Django 5.2.3 on 2025-06-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_about_founder_image_alter_about_founder_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Provide',
        ),
        migrations.AlterModelOptions(
            name='provide',
            options={'ordering': ['id'], 'verbose_name': 'Предоставляемая услуга', 'verbose_name_plural': 'Предоставляемые услуги'},
        ),
    ]
