# Generated by Django 5.2 on 2025-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contactrequest_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField()),
                ('founder_name', models.CharField(max_length=100)),
                ('founder_role', models.CharField(max_length=100)),
                ('founder_image', models.ImageField(upload_to='founders/')),
            ],
        ),
    ]
