# Generated by Django 5.2 on 2025-05-16 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_consult_rename_category_review_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
