# Generated by Django 5.2 on 2025-05-21 04:27

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.CharField(
                choices=[
                    ('Frontend', 'Frontend'),
                    ('Backend', 'Backend'),
                    ('Design', 'Дизайн'),
                    ('Management', 'Менеджмент'),
                    ('SMM', 'SMM')
                ],
                default='Frontend',  # ✅ строка, соответствующая choices
                max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime.now  # ✅ правильный default
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='level',
            field=models.CharField(
                choices=[
                    ('Intern', 'Intern'),
                    ('Junior', 'Junior'),
                    ('Middle', 'Middle'),
                    ('Senior', 'Senior')
                ],
                default='Intern',  # ✅ строка
                max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='work_type',
            field=models.CharField(
                choices=[
                    ('Remote', 'Удалённо'),
                    ('Office', 'Офис'),
                    ('Hybrid', 'Гибридный график'),
                    ('Full-time', 'Полный рабочий день')
                ],
                default='Remote',  # ✅ строка
                max_length=20
            ),
            preserve_default=False,
        ),
    ]
