# Generated by Django 5.2 on 2025-05-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_jobapplication_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['id'], 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='consult',
            options={'ordering': ['id'], 'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['id'], 'verbose_name': 'Контактная заявка', 'verbose_name_plural': 'Контактные заявки'},
        ),
        migrations.AlterModelOptions(
            name='dizain',
            options={'ordering': ['id'], 'verbose_name': 'Дизайн', 'verbose_name_plural': 'Дизайны'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['id'], 'verbose_name': 'Заявка на вакансию', 'verbose_name_plural': 'Заявки на вакансии'},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['id'], 'verbose_name': 'Панель', 'verbose_name_plural': 'Панели'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['id'], 'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
    ]
