# Generated by Django 5.2 on 2025-05-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_meropriyatie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
