# Generated by Django 5.2 on 2025-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_panel_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(),
        ),
    ]
