# Generated by Django 5.2 on 2025-06-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_consult_text_alter_review_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
